
CREATE TABLE IF NOT EXISTS platform_fees (
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    platform_id INTEGER NOT NULL REFERENCES platforms(platform_id),
    platform_fee_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fee_type VARCHAR NOT NULL,
    cost DECIMAL(19, 4) NOT NULL
);