CREATE TABLE IF NOT EXISTS item_location {    
    location_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    location_name VARCHAR NOT NULL,
    location_area VARCHAR NOT NULL
}