CREATE TABLE IF NOT EXISTS subcategory (
    category_id INTEGER NOT NULL REFERENCES category(category_id),
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    subcategory_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR NOT NULL
);