CREATE TABLE IF NOT EXISTS item (
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    platform_id INTEGER NOT NULL REFERENCES platforms(platform_id),
    location_id INTEGER NOT NULL REFERENCES item_location(location_id),
    category_id INTEGER NOT NULL REFERENCES category(category_id),
    subcategory_id INTEGER NOT NULL REFERENCES subcategory(subcategory_id),
    item_name VARCHAR NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now(),
    cost DECIMAL(19, 4) NOT NULL NOT NULL,
    quantity INTEGER NOT NULL,
    is_sold BOOLEAN,
    date_sold DATE,
    sold_for DECIMAL(19, 4) NOT NULL,
    fees DECIMAL(19, 4) NOT NULL,
    shipping_cost DECIMAL(19, 4) NOT NULL
);